# Generated by Django 3.2 on 2022-12-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, help_text='Please enter Initials / Middle Name', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter Initials / Last Name', max_length=30, null=True)),
                ('full_name', models.CharField(editable=False, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Patient - Basic Data',
                'verbose_name_plural': 'Patient - Basic Data',
                'ordering': ('first_name', 'middle_name', 'last_name', 'age', 'sex'),
            },
        ),
        migrations.CreateModel(
            name='VitalCNS',
            fields=[
                ('vitalcns_id', models.AutoField(primary_key=True, serialize=False, verbose_name='VitalCNS_ID')),
                ('gcs', models.CharField(blank=True, max_length=50, null=True, verbose_name='GCS')),
                ('hmf', models.CharField(blank=True, max_length=50, null=True, verbose_name='HMF')),
                ('ms_tone_ul_r', models.CharField(blank=True, default='N', max_length=50, null=True, verbose_name='TONE UL R')),
                ('ms_tone_ul_l', models.CharField(blank=True, default='N', max_length=50, null=True, verbose_name='TONE UL L')),
                ('ms_tone_ll_r', models.CharField(blank=True, default='N', max_length=50, null=True, verbose_name='TONE LL R')),
                ('ms_tone_ll_l', models.CharField(blank=True, default='N', max_length=50, null=True, verbose_name='TONE LL L')),
                ('ms_dtr_b_r', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR B R')),
                ('ms_dtr_b_l', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR B L')),
                ('ms_dtr_t_r', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR T R')),
                ('ms_dtr_t_l', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR T L')),
                ('ms_dtr_s_r', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR S R')),
                ('ms_dtr_s_l', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR S L')),
                ('ms_dtr_k_r', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR K R')),
                ('ms_dtr_k_l', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR K L')),
                ('ms_dtr_a_r', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR A R')),
                ('ms_dtr_a_l', models.CharField(blank=True, default='2+', max_length=50, null=True, verbose_name='DTR A L')),
                ('ms_dtr_plorter_r', models.CharField(blank=True, default='↓', max_length=50, null=True, verbose_name='DTR PLORTER R')),
                ('ms_dtr_plorter_l', models.CharField(blank=True, default='↓', max_length=50, null=True, verbose_name='DTR PLORTER L')),
                ('ms_power_ul_r', models.CharField(blank=True, default='5/5', max_length=50, null=True, verbose_name='POWER UL R')),
                ('ms_power_ul_l', models.CharField(blank=True, default='5/5', max_length=50, null=True, verbose_name='POWER UL L')),
                ('ms_power_ll_r', models.CharField(blank=True, default='5/5', max_length=50, null=True, verbose_name='POWER LL R')),
                ('ms_power_ll_l', models.CharField(blank=True, default='5/5', max_length=50, null=True, verbose_name='POWER LL L')),
                ('ss_touch', models.CharField(blank=True, default='B/L N', max_length=50, null=True, verbose_name='TOUCH ')),
                ('ss_temp', models.CharField(blank=True, default='B/L N', max_length=50, null=True, verbose_name='PAIN ')),
                ('ss_pain', models.CharField(blank=True, default='B/L N', max_length=50, null=True, verbose_name='TEMPERATURE ')),
                ('ss_gps', models.CharField(blank=True, default='B/L N', max_length=50, null=True, verbose_name='GPS')),
                ('cerebelleim', models.CharField(blank=True, default='ABSENT', max_length=50, null=True, verbose_name='Cerebellum')),
                ('gait', models.CharField(blank=True, default='N', max_length=50, null=True, verbose_name='GAIT')),
                ('muscle_bulk', models.CharField(blank=True, default='N', max_length=50, null=True, verbose_name='MUSCLE BULK')),
                ('nutrition', models.CharField(blank=True, default='N', max_length=50, null=True, verbose_name='NUTRITION')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vital_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('oe', models.CharField(blank=True, max_length=30, null=True)),
                ('p_ce_cn_iol', models.CharField(blank=True, max_length=30, null=True)),
                ('temp', models.CharField(blank=True, max_length=30, null=True)),
                ('pulse', models.CharField(blank=True, max_length=30, null=True)),
                ('bp', models.CharField(blank=True, max_length=30, null=True)),
                ('rr', models.CharField(blank=True, max_length=30, null=True)),
                ('cns', models.CharField(blank=True, max_length=30, null=True)),
                ('chest', models.CharField(blank=True, max_length=30, null=True)),
                ('cvs', models.CharField(blank=True, max_length=30, null=True)),
                ('pa', models.CharField(blank=True, max_length=30, null=True)),
                ('tests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
