# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, help_text='Please enter Initials / Middle Name', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter Initials / Last Name', max_length=30, null=True)),
                ('full_name', models.CharField(editable=False, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6)),
            ],
            options={
                'ordering': ('first_name', 'middle_name', 'last_name', 'age', 'sex'),
                'verbose_name': 'Patient - Basic Data',
                'verbose_name_plural': 'Patient - Basic Data',
            },
        ),
    ]
