# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171031_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vital_id', models.AutoField(primary_key=True, serialize=False)),
                ('weigth', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('oe', models.CharField(blank=True, max_length=30, null=True)),
                ('p_ce_cn_iol', models.CharField(blank=True, max_length=30, null=True)),
                ('temp', models.CharField(blank=True, max_length=30, null=True)),
                ('pulse', models.CharField(blank=True, max_length=30, null=True)),
                ('bp', models.CharField(blank=True, max_length=30, null=True)),
                ('rr', models.CharField(blank=True, max_length=30, null=True)),
                ('cns', models.CharField(blank=True, max_length=30, null=True)),
                ('chest', models.CharField(blank=True, max_length=30, null=True)),
                ('cvs', models.CharField(blank=True, max_length=30, null=True)),
                ('pa', models.CharField(blank=True, max_length=30, null=True)),
                ('tests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
