# Generated by Django 3.2 on 2022-12-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergic_to', models.CharField(max_length=100)),
                ('reaction_observed', models.CharField(choices=[('rash', 'Rash'), ('angioedema', 'Angioedema'), ('anaphylaxis', 'Anaphylaxis')], default='Rash', max_length=100)),
                ('patient_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient')),
            ],
        ),
    ]
