# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication_list', '0001_initial'),
        ('complaints', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=datetime.datetime(2017, 10, 29, 5, 44, 56, 309596, tzinfo=utc))),
                ('duration', models.CharField(help_text='Number of day or months', max_length=100)),
                ('remarks', models.TextField(default='NAD', help_text='limit to 200 words', max_length=200)),
                ('complaints', models.ManyToManyField(blank=True, to='complaints.Complaints')),
                ('diagnose', models.ManyToManyField(blank=True, to='complaints.Disease')),
                ('medicines', models.ManyToManyField(to='medication_list.MedicationList')),
                ('patient_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
    ]
