# Generated by Django 3.2 on 2022-12-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('medication_list', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(blank=True, help_text='Number of day or months', max_length=100, null=True)),
                ('remarks', models.TextField(default='NAD', help_text='limit to 200 words', max_length=200)),
                ('cns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vitalcns')),
                ('complaints', models.ManyToManyField(blank=True, to='complaints.Complaints')),
                ('diagnose', models.ManyToManyField(blank=True, to='complaints.Disease')),
                ('medicines', models.ManyToManyField(to='medication_list.MedicationList')),
                ('vitals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vitals')),
            ],
        ),
        migrations.CreateModel(
            name='VisitContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('patient_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient')),
                ('visits', models.ManyToManyField(blank=True, to='visit.Visit')),
            ],
        ),
    ]
