# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20171029_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='id',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
