# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vitals'),
        ('visit', '0003_auto_20171031_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vitals'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='duration',
            field=models.CharField(blank=True, help_text='Number of day or months', max_length=100, null=True),
        ),
    ]
