# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180114_0929'),
        ('visit', '0004_auto_20171114_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='OPEN', help_text='OPEN/CLOSED', max_length=50)),
                ('patient_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient_detail',
        ),
        migrations.AddField(
            model_name='visitcontainer',
            name='visits',
            field=models.ManyToManyField(blank=True, to='visit.Visit'),
        ),
    ]
