# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_auto_20180224_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitcontainer',
            name='status',
        ),
    ]
