# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=history.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, max_length=500, null=True, verbose_name='Status')),
                ('date_of_diagnosis', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=None, verbose_name='Active?')),
                ('infectious_disease', models.BooleanField(default=None)),
                ('allergic_disease', models.BooleanField(default=None)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Disease')),
                ('patient_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
    ]
