# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalfiles',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='id',
        ),
        migrations.AddField(
            model_name='medicalfiles',
            name='medical_files_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='medicine_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
