# Generated by Django 3.2 on 2022-12-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True, verbose_name='Detail about the problem')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symptoms', models.ManyToManyField(blank=True, to='complaints.Complaints')),
            ],
        ),
    ]
