# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='id',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='id',
        ),
        migrations.AddField(
            model_name='complaints',
            name='complain_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
