# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-10 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20171031_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
