# Generated by Django 3.2 on 2022-12-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationList',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Choose from list given...', max_length=100)),
                ('medicine', models.CharField(help_text='Only Generic Names..', max_length=100)),
                ('dosage', models.CharField(help_text='100mg or 500mg etc.', max_length=100)),
                ('frequency', models.CharField(help_text='Number of times to be taken in 1 day', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='Number of day or months', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='limit to 200 words', max_length=200, null=True)),
                ('category', models.CharField(blank=True, help_text='Catagory of the Drug', max_length=100, null=True)),
            ],
        ),
    ]
