# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TAB', 'Tablet'), ('CAP', 'Capsule'), ('SAC', 'Sachets'), ('SYR', 'Syrups'), ('INJ', 'Injection')], help_text='Choose from list given...', max_length=100)),
                ('medicine', models.CharField(help_text='Only Generic Names..', max_length=100)),
                ('dosage', models.CharField(help_text='100mg or 500mg etc.', max_length=100)),
                ('frequency', models.CharField(help_text='Number of times to be taken in 1 day', max_length=100)),
            ],
        ),
    ]
