# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationlist',
            name='id',
        ),
        migrations.AddField(
            model_name='medicationlist',
            name='duration',
            field=models.CharField(blank=True, help_text='Number of day or months', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicationlist',
            name='medication_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationlist',
            name='type',
            field=models.CharField(help_text='Choose from list given...', max_length=100),
        ),
    ]
