# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_list', '0002_auto_20171112_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlist',
            name='category',
            field=models.CharField(blank=True, help_text='Catagory of the Drug', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicationlist',
            name='remarks',
            field=models.TextField(blank=True, help_text='limit to 200 words', max_length=200, null=True),
        ),
    ]
